### ISSUE TITLE
[Bug] You stumbled upon a bug in the source code

### ISSUE THREAD

**Issue by codefln** [brillout/vite-plugin-server-entry#11]
Error: [@brillout/vite-plugin-server-entry@0.4.6][Bug] You stumbled upon a bug in the source code of @brillout/vite-plugin-server-entry. Reach out at https://github.com/brillout/vite-plugin-server-entry/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes @brillout/vite-plugin-server-entry more robust.
    at crawlServerEntryFileWithNodeJs (/Users/codefln/code/myapp/serv/node_modules/@brillout/vite-plugin-server-entry/dist/importServerEntry/index.js:131:24)
    at async importServerEntry (/Users/codefln/code/myapp/serv/node_modules/@brillout/vite-plugin-server-entry/dist/importServerEntry/index.js:46:19)
    at async loadImportBuild (file:///Users/codefln/code/myapp/serv/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:9)
    at async initGlobalContext (file:///Users/codefln/code/myapp/serv/node_modules/vike/dist/esm/node/runtime/globalContext.js:109:30)
    at async renderPageAndPrepare (file:///Users/codefln/code/myapp/serv/node_modules/vike/dist/esm/node/runtime/renderPage.js:64:9)
    at async renderPage_wrapper (file:///Users/codefln/code/myapp/serv/node_modules/vike/dist/esm/node/runtime/renderPage.js:26:24)
    at async renderPage (file:///Users/codefln/code/myapp/serv/node_modules/vike/dist/esm/node/runtime/renderPage.js:45:35)

**Comment by brillout** [comment]
Hm, that's quite unexpected. Can you publish a reproduction?

**Comment by codefln** [comment]
I figured it out! This error occurred because of my incorrect Vite config. I had an option:

rollupOptions: {
      input: {
        sw: `${__dirname}/src/sw.js`,
      },
      output: {
        entryFileNames: (assetInfo) => {
          if (assetInfo.name === 'sw') {
            return 'sw.js';
          }
        
          return '[name]-[hash].js';
        },
      },
    },

**Comment by brillout** [comment]
Thank you for circling back on this. The error message is now much improved. Also thank you a lot for sponsoring :green_heart: it makes a significant difference!
