### ISSUE TITLE
Production build with "telefunc/vite" plugin throws error

### ISSUE THREAD

**Issue by shimarulin** [brillout/vite-plugin-server-entry#9]
I create new project from https://github.com/bluwy/create-vite-extra/tree/master/template-ssr-vue-ts template and add telefunc as described in https://github.com/brillout/telefunc/tree/main/examples/vite. Dev mode works fine, but production build fails. I was trying to upgrade packages to latest versions, but the issue still persists.

Repository to reproduce: https://github.com/shimarulin/vite-vue-telefunc-example

Environment:

```
❯ node -v                 
v20.11.1

❯ npm -v             
10.2.4
```

```
❯ npm run build        

> vite-vue-telefunc@0.0.0 build
> npm run build:client && npm run build:server


> vite-vue-telefunc@0.0.0 build:client
> vite build --ssrManifest --outDir dist/client

vite v5.2.6 building for production...
✓ 52 modules transformed.
dist/client/index.html                  0.50 kB │ gzip:  0.32 kB
dist/client/.vite/ssr-manifest.json     2.71 kB │ gzip:  0.64 kB
dist/client/assets/index-DdphExTw.css   1.53 kB │ gzip:  0.71 kB
dist/client/assets/index-CG6vEnyb.js   71.82 kB │ gzip: 28.42 kB
✓ built in 559ms

> vite-vue-telefunc@0.0.0 build:server
> vite build --ssr src/entry-server.ts --outDir dist/server

vite v5.2.6 building SSR bundle for production...
✓ 14 modules transformed.
x Build failed in 1.05s
error during build:
Error: [@brillout/vite-plugin-server-entry@0.4.4][Bug] You stumbled upon a bug in the source code of @brillout/vite-plugin-server-entry. Reach out at https://github.com/brillout/vite-plugin-server-entry/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes @brillout/vite-plugin-server-entry more robust.
    at findServerEntry (/home/shimarulin/vite-vue-telefunc-example/node_modules/@brillout/vite-plugin-server-entry/dist/plugin/index.js:336:24)
    at Object.generateBundle (/home/shimarulin/vite-vue-telefunc-example/node_modules/@brillout/vite-plugin-server-entry/dist/plugin/index.js:87:31)
    at file:///home/shimarulin/vite-vue-telefunc-example/node_modules/rollup/dist/es/shared/node-entry.js:19563:40
```

**Comment by brillout** [comment]
I could indeed reproduce, I will dig & fix later today.

**Comment by brillout** [comment]
It seems to be a Vite bug. (Setting the build server entry with `bulid.ssr` i.e. `--ssr path/to/entry.js` erases all other server entries including the one added by `@brillout/vite-plugin-server-entry`.)

Workaround: https://github.com/brillout/vite-vue-telefunc-example/commit/05fcc94e362d58e8a576616206a5e7a2d1ad11ec.

**Comment by shimarulin** [comment]
Big thanks!

**Comment by brillout** [comment]
Sure & let me know if you run into other issues.

(Btw. in case your company is up for it, we're looking for [sponsors](https://github.com/vikejs/vike/issues/1350) &mdash; it makes a massive difference.)
